### PR TITLE
Fix Hoarcekat stories erroring

### LINKED ISSUE #45: Hoarcekat stories seem broken
Repro steps:
1. Sync dev.project.json
2. Open Example/Hoarcekat.story
3. setState error

This is likely related to #42 where I made changes to how StoryView works

### PR DESCRIPTION
**Pull request by vocksel**
Resolves #45

Calling `setErr()` without a condition was leading to repeated state updates. Even though the values were not changing (i.e. `setErr()` was being called with a value of `nil` each time), it still results in state updates for some reason.

This might be a bug with RoactHooks. In the meantime, a condition is being used to ensure state updates only if there is an error.

### CODE REVIEW

File: src/Components/StoryView.lua [hunk 1]
```diff
@@ -87,17 +87,19 @@ local function StoryView(props: Props, hooks: any)
...
-				setErr(if success then nil else result)
-
 				if success then
-					tree.value = result
+					if err then
+						setErr(nil)
+					end
+				else
+					setErr(result)
 				end
```
Comment (vocksel) [inline src/Components/StoryView.lua:99]: Is there a better way to do this? Simply running `setErr(if success then nil else result)` leads to an infinite state update. No idea why

Comment (passhley) [reply src/Components/StoryView.lua:99]: I don't believe there is a better way for this unfortunately. Either way, the more explicit, the better.

**Review by passhley — APPROVED** [review]
